package com.fs.mapper;

import com.fs.po.Record;

public interface RecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table record
     *
     * @mbggenerated Tue Jul 16 13:55:22 GMT+08:00 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table record
     *
     * @mbggenerated Tue Jul 16 13:55:22 GMT+08:00 2019
     */
    int insert(Record record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table record
     *
     * @mbggenerated Tue Jul 16 13:55:22 GMT+08:00 2019
     */
    int insertSelective(Record record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table record
     *
     * @mbggenerated Tue Jul 16 13:55:22 GMT+08:00 2019
     */
    Record selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table record
     *
     * @mbggenerated Tue Jul 16 13:55:22 GMT+08:00 2019
     */
    int updateByPrimaryKeySelective(Record record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table record
     *
     * @mbggenerated Tue Jul 16 13:55:22 GMT+08:00 2019
     */
    int updateByPrimaryKeyWithBLOBs(Record record);
}