package com.fs.mapper;

import com.fs.po.Stu;

public interface StuMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stu
     *
     * @mbggenerated Tue Jul 16 13:55:22 GMT+08:00 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stu
     *
     * @mbggenerated Tue Jul 16 13:55:22 GMT+08:00 2019
     */
    int insert(Stu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stu
     *
     * @mbggenerated Tue Jul 16 13:55:22 GMT+08:00 2019
     */
    int insertSelective(Stu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stu
     *
     * @mbggenerated Tue Jul 16 13:55:22 GMT+08:00 2019
     */
    Stu selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stu
     *
     * @mbggenerated Tue Jul 16 13:55:22 GMT+08:00 2019
     */
    int updateByPrimaryKeySelective(Stu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stu
     *
     * @mbggenerated Tue Jul 16 13:55:22 GMT+08:00 2019
     */
    int updateByPrimaryKey(Stu record);
}