package com.fs.mapper;

import com.fs.po.Type;

public interface TypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table type
     *
     * @mbggenerated Tue Jul 16 13:55:22 GMT+08:00 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table type
     *
     * @mbggenerated Tue Jul 16 13:55:22 GMT+08:00 2019
     */
    int insert(Type record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table type
     *
     * @mbggenerated Tue Jul 16 13:55:22 GMT+08:00 2019
     */
    int insertSelective(Type record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table type
     *
     * @mbggenerated Tue Jul 16 13:55:22 GMT+08:00 2019
     */
    Type selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table type
     *
     * @mbggenerated Tue Jul 16 13:55:22 GMT+08:00 2019
     */
    int updateByPrimaryKeySelective(Type record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table type
     *
     * @mbggenerated Tue Jul 16 13:55:22 GMT+08:00 2019
     */
    int updateByPrimaryKey(Type record);
}