package com.fs.po;

public class Record {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column record.id
     *
     * @mbggenerated Tue Jul 16 13:55:22 GMT+08:00 2019
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column record.mytinyblob
     *
     * @mbggenerated Tue Jul 16 13:55:22 GMT+08:00 2019
     */
    private byte[] mytinyblob;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column record.myblob
     *
     * @mbggenerated Tue Jul 16 13:55:22 GMT+08:00 2019
     */
    private byte[] myblob;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column record.mymediumblob
     *
     * @mbggenerated Tue Jul 16 13:55:22 GMT+08:00 2019
     */
    private byte[] mymediumblob;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column record.mylongblob
     *
     * @mbggenerated Tue Jul 16 13:55:22 GMT+08:00 2019
     */
    private byte[] mylongblob;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column record.id
     *
     * @return the value of record.id
     *
     * @mbggenerated Tue Jul 16 13:55:22 GMT+08:00 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column record.id
     *
     * @param id the value for record.id
     *
     * @mbggenerated Tue Jul 16 13:55:22 GMT+08:00 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column record.mytinyblob
     *
     * @return the value of record.mytinyblob
     *
     * @mbggenerated Tue Jul 16 13:55:22 GMT+08:00 2019
     */
    public byte[] getMytinyblob() {
        return mytinyblob;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column record.mytinyblob
     *
     * @param mytinyblob the value for record.mytinyblob
     *
     * @mbggenerated Tue Jul 16 13:55:22 GMT+08:00 2019
     */
    public void setMytinyblob(byte[] mytinyblob) {
        this.mytinyblob = mytinyblob;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column record.myblob
     *
     * @return the value of record.myblob
     *
     * @mbggenerated Tue Jul 16 13:55:22 GMT+08:00 2019
     */
    public byte[] getMyblob() {
        return myblob;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column record.myblob
     *
     * @param myblob the value for record.myblob
     *
     * @mbggenerated Tue Jul 16 13:55:22 GMT+08:00 2019
     */
    public void setMyblob(byte[] myblob) {
        this.myblob = myblob;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column record.mymediumblob
     *
     * @return the value of record.mymediumblob
     *
     * @mbggenerated Tue Jul 16 13:55:22 GMT+08:00 2019
     */
    public byte[] getMymediumblob() {
        return mymediumblob;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column record.mymediumblob
     *
     * @param mymediumblob the value for record.mymediumblob
     *
     * @mbggenerated Tue Jul 16 13:55:22 GMT+08:00 2019
     */
    public void setMymediumblob(byte[] mymediumblob) {
        this.mymediumblob = mymediumblob;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column record.mylongblob
     *
     * @return the value of record.mylongblob
     *
     * @mbggenerated Tue Jul 16 13:55:22 GMT+08:00 2019
     */
    public byte[] getMylongblob() {
        return mylongblob;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column record.mylongblob
     *
     * @param mylongblob the value for record.mylongblob
     *
     * @mbggenerated Tue Jul 16 13:55:22 GMT+08:00 2019
     */
    public void setMylongblob(byte[] mylongblob) {
        this.mylongblob = mylongblob;
    }
}